/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_micronet_canbus_FlexCANCanbusInterfaceBridge */

extern "C" {
    /*
     * Class:     com_micronet_canbus_FlexCANCanbusInterfaceBridge
     * Method:    createInterface
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_com_micronet_canbus_FlexCANCanbusInterfaceBridge_createInterface(JNIEnv *env, jobject obj);

};