/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_micronet_canbus_FlexCANCanbusInterfaceBridge */

#define CAN1_TTY    "/dev/ttyACM2"
#define CAN2_TTY    "/dev/ttyACM3"
#define J1708_TTY   "/dev/ttyACM4"

extern "C" {
    /*
     * Class:     com_micronet_canbus_FlexCANCanbusInterfaceBridge
     * Method:    createInterface
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_com_micronet_canbus_FlexCANCanbusInterfaceBridge_createInterface(JNIEnv *env, jobject obj);

};